#!/bin/bash

#This will replace everything in my .bashrc, and add my personal alias

#.bashrc
echo"# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
PS1='[\u@\h \W]\$ '

#commands

alias update='sudo pacman -Syu'

alias install='sudo pacman -S'

alias remove='sudo pacman -Rs'

alias get='git clone'

alias halt='shutdown now'

#aur packages 

alias chrome='https://aur.archlinux.org/google-chrome.git'

alias minecraft='https://aur.archlinux.org/minecraft-launcher.git'

alias balena-etcher='https://aur.archlinux.org/balena-etcher.git'

alias parsec-bin='https://aur.archlinux.org/parsec-bin.git'

alias timeshift='https://aur.archlinux.org/timeshift.git'" | tee ~/$USER/.bashrc

source .bashrc
