#!/bin/bash

#This will replace everything in my .bashrc, and add my personal alias

#.bashrc
echo "#commands

alias update='sudo pacman -Syu'

alias install='sudo pacman -S'

alias remove='sudo pacman -Rs'

alias get='git clone'

alias delete='rm -R'

alias halt='shutdown now'


&& echo 'finished moving all alias'


