#!/bin/bash

#This will ad # Check for other operating systems
GRUB_DISABLE_OS_PROBER=false
to /etc/default/grub

echo '# Check for other operating systems
      GRUB_DISABLE_OS_PROBER=false' | tee -a /etc/default/grub && echo'success!'
